import {RequestValidate} from "../../common/otp.model";

export interface BeneficiaryInternationalAddRequestModel  {
    beneficiaryCategory: string;
    countryCode: string;
    countryNameEnglish: string;
    swiftCode: string;
    bankName: string;
    bankAddress: string;
    branchAddress: string;
    currency: string;
    beneficiaryAccount: string;
    branchCode: string;
    branchName: string;
    shortCode: string;
    firstName: string;
    secondName: string;
    middleName: string;
    lastName: string;
    nationality: string;
    mobileNo: string;
    email: string;
    dateBirth: string;
    placeBirth: string;
    addressLine1: string;
    addressLine2: string;
    streetNo: string;
    pobox: string;
    cityState: string;
    addressRegion: string;
    addressPostalCode: string;
    idType: string;
    idNumber: string;
    issueAt: string;
    issueDate: string;
    countryIssue: string;
    documentSortCode: string;
    telephoneNoPrefix: string;
    telephoneNoArea: string;
    telephoneNo: string;
    telephoneNoExtension: string;
    requestValidate: RequestValidate;
}
export interface BeneficiaryInternationalAddV2RequestModel {
    beneficiaryType?: string | null;
    productType: string;
    serviceType: string;
    countryNumber?: string;
    erNumber?: string;
    ercicNum?: string;
    category?: string;
    subCategory?: string;
    paymentMethod?: string;
    benefSwiftName?: string;
    benefFirstName: string;
    benefSecondName?: string;
    benefThirdName?: string;
    benefLastName: string;
    benefFullName?: string | null;
    benefNickname?: string;
    juridicalStatus: string;
    idType?: string;
    idNumber?: string;
    benefNationality?: string;
    docIssuePlace?: string;
    docIssueDate?: string;
    docExpiryDate?: string;
    docIssueCountry?: string;
    docRegion?: string;
    benefBirthDate: string;
    benefBirthPlace?: string;
    benefAddress?:string | null;
    benefAddress2?: string;
    benefAddress3?: string;
    benefAddress4?: string;
    benefAddressNum?: string;
    benefCountry: string;
    benefCountyDistrict?: string;
    benefRegion?: string;
    benefCity?: string;
    benefPostCode?: string;
    benefPOBox?: string;
    benefPhonePrefix?: string;
    benefPhoneArea?: string;
    benefPhoneNum?: string;
    pobox: string;
    benefPhoneXtn?: string;
    benefMobilePrefix?: string | null;
    benefMobileArea?: string;
    benefMobileNum: string;
    benefEmail?: string;
    correspondantIdType?: string;
    correspondantId?: string;
    correspondantBranchId?: string;
    intermediaryIdType?: string;
    intermediaryId?: string;
    intermediaryBranchId?: string;
    intermediaryCountry?: string;
    ultimateCreditorFullName?: string;
    ultimateCreditorCountry?: string;
    ultimateCreditorBirthDate?: string;
    ultimateCreditorBirthPlace?: string;
    benefCardNumber?: string;
    benefCardIssuerName?: string;
    benefCardExpiryDate?: string;
    benefCardBranch?: string;
    benefIcon?: string | null;
    payOnValidPhoto?: true;
    messageToBeneficiary?: string;
    question?: string;
    answer?: string;
    beneficiaryAdditionalInfo?: string;
    beneficiaryAdditionalInfo1?: string;
    beneficiaryAdditionalInfo2?: string;
    beneficiaryAdditionalInfo3?: string;
    beneficiaryAdditionalInfo4?: string;
    beneficiaryAdditionalInfo5?: string;
    beneficiaryAdditionalInfo6?: string;
    favoriteFlag?: true;
    benefExpiryDate?: string;
    benefBankAcct: string | null;
    benefBanckAccountType?: string;
    benefBankIBAN?: string | null;
    benefBankCode?: string;
    benefBankName: string;
    benefBankCountry?: string;
    benefBankIdType?: string;
    benefBankId: string;
    benefBranchName: string;
    benefBranchCode?: string;
    beneficiaryBranchDtls?: string | null;
    benefCurrency: string;
    benefSWIFTCode?: string;
    benefSortCode?: string;
    benefIFSCCode?: string;
    routingStatus?: string;
    routingIndex?: string;
    routingCode?: string;
    routingBeneficiaryCode?: string;
    remitLinkTypeCode?: string;
    remitLinkDesc?: string;
    beneficiaryIndianBankCtry?: string | null;
    h2hBeneficiaryAccountStatus?: string;
    h2hActivationDate?: string;
    benefRelation?: string;
    remitLinkTypeDesc?: string;
    requestValidate?: RequestValidate
    language?: string
}
